# Generated by Django 5.1.7 on 2025-04-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='task_id')),
                ('answer_key', models.TextField(verbose_name='Правильный ответ')),
                ('alternative_ansvers', models.TextField(verbose_name='Прочие ответы')),
                ('explanation', models.TextField(verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Ключи/ответы к заданию',
                'verbose_name_plural': 'Ключи/ответы к заданиям',
                'ordering': ['task_id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(default='Описание', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория задания',
                'verbose_name_plural': 'Категории заданий',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result_criteria_scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='Результат')),
                ('criteria_id', models.IntegerField(verbose_name='Критерий')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Баллы')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Детализация оценок по критерию',
                'verbose_name_plural': 'Детализации оценок по критериям',
            },
        ),
        migrations.CreateModel(
            name='Student_task_resuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='Результат')),
                ('student_id', models.IntegerField(verbose_name='Студент')),
                ('task_id', models.IntegerField(verbose_name='Задание')),
                ('submission_date', models.DateTimeField(verbose_name='Дата выполнения')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Всего баллов')),
                ('feedback', models.TextField(verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name': 'Результат выполнения заданий по студенту',
                'verbose_name_plural': 'Результаты выполнения заданий по студенту',
                'ordering': ['student_id', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('difficulty_level', models.IntegerField(verbose_name='Сложность')),
                ('max_score', models.IntegerField(verbose_name='Макс.балл')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task_category_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='Задание')),
                ('category_id', models.IntegerField(verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Связь между заданиями и категориями',
                'verbose_name_plural': 'Связи между заданиями и категориями',
                'ordering': ['-category_id', '-task_id'],
            },
        ),
        migrations.CreateModel(
            name='Task_criteria_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='ссылка на Задание')),
                ('criteria_id', models.IntegerField(verbose_name='ссылка на Критерий')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес')),
                ('max_points', models.IntegerField(verbose_name='Максимально пунктов')),
            ],
            options={
                'verbose_name': 'Связь между заданиями и критериями с весами',
                'verbose_name_plural': 'Связи между заданиями и критериями с весами',
                'ordering': ['task_id', 'criteria_id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('variant_id', models.IntegerField(verbose_name='Номер варианта')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['-created_at', '-variant_id'],
            },
        ),
        migrations.CreateModel(
            name='Variant_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField(verbose_name='Вариант')),
                ('task_id', models.IntegerField(verbose_name='Задача')),
                ('task_order', models.IntegerField(verbose_name='Номер задачи в варианте')),
            ],
            options={
                'verbose_name': 'Задача варианта',
                'verbose_name_plural': 'Задачи варианта',
                'ordering': ['variant_id', 'task_id', 'task_order'],
            },
        ),
    ]
