# Generated by Django 5.1.7 on 2025-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.TextField(blank=True, default='Вопрос..', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='task',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answers', to='tasks.answer'),
        ),
    ]
