# Generated by Django 5.1.7 on 2025-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_answer_question_task_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.answer'),
        ),
    ]
