# Generated by Django 5.1.7 on 2025-04-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_head_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='alternative_ansvers',
            new_name='alternative_answers',
        ),
    ]
