# Generated by Django 5.1.7 on 2025-04-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_alternative_ansvers_answer_alternative_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task_category_mapping',
        ),
        migrations.DeleteModel(
            name='Variant_tasks',
        ),
        migrations.AddField(
            model_name='variant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tasks.category'),
        ),
        migrations.AddField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.task'),
        ),
    ]
