# Generated by Django 5.1.7 on 2025-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_task_category_mapping_delete_variant_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='variants', to='tasks.task'),
        ),
    ]
