# Generated by Django 5.1.7 on 2025-04-12 09:51

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_variant_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='head_answers',
            field=models.JSONField(blank=True, default=tasks.models.default_head_answers, verbose_name='Заголовки вопросов-ответов'),
        ),
    ]
